import { Geist, Geist_Mono, Source_Sans_3 } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import ContentWrapper from "@/components/ContentWrapper";

const geistSans = Source_Sans_3({
  weight: ["200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ['latin']
})

export const metadata = {
  title: "Anas Mart",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.className} antialiased`}
      >
        <ContentWrapper>
          <Navbar />
          {children}
        </ContentWrapper>
      </body>
    </html>
  );
}
